// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoztz2A0ptPVeB7u6gId7SDdIyLdUodHU',
    appId: '1:476348021342:web:f1b44f07fe2093d03812cf',
    messagingSenderId: '476348021342',
    projectId: 'mywaylearn',
    authDomain: 'mywaylearn.firebaseapp.com',
    storageBucket: 'mywaylearn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJLMfqLiG7KO9bxobjTsZbQ_f-Jvotc4',
    appId: '1:476348021342:android:a9b0761d70e8ab983812cf',
    messagingSenderId: '476348021342',
    projectId: 'mywaylearn',
    storageBucket: 'mywaylearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDab3qq3HoQ3_R9JMhxuYiqEJx5yrXiqQE',
    appId: '1:476348021342:ios:150eafba12a4d4783812cf',
    messagingSenderId: '476348021342',
    projectId: 'mywaylearn',
    storageBucket: 'mywaylearn.appspot.com',
    iosClientId: '476348021342-7le6947iuok1s3bes6i0p07d5a31nlh9.apps.googleusercontent.com',
    iosBundleId: 'com.ninetail.mywaylearn',
  );
}
